import re
import sys

filepath = r"C:\Users\lorra\projects\ai-infra-manager\skills\tech\algorithms\LeetCode Problem Collection.md"

# slug -> Chinese annotation
translations = {
    # Linked List
    "add-two-numbers": "两链表同步迭代进位求和",
    "merge-two-sorted-lists": "哑节点+双指针合并有序链表",
    "merge-k-sorted-lists": "最小堆比较节点值，反复提取最小",
    "remove-nth-node-from-end": "哑头节点，快慢指针间距N，落点为待删前驱",
    "reverse-nodes-in-k-group": "递归取后继头节点，逆转k节后接后继",
    "rotate-list": "三次反转法：整体→前K→后K",
    "remove-duplicates-ii": "带prev的快慢指针跳过重复段，或分成dup/noDup两链",
    "remove-duplicates-from-sorted-list": "快慢指针去重",
    "remove-duplicates-from-sorted-list-ii": "带prev的快慢指针跳过重复段",
    "partition-list": "两哑节点分低高两链，尾部相接",
    "reverse-linked-list-ii": "递归推进到m位，触发k节逆转逻辑",
    "copy-list-with-random-pointer": "两遍：建旧→新映射后赋next和random",
    "linked-list-cycle": "快慢指针，相遇则有环",
    "linked-list-cycle-ii": "快慢相遇后，一指针回头，再次相遇为环入口",
    "reorder-list": "栈存后半，交替拼接原链表与倒序尾节点",
    "intersection-of-two-lists": "A+B与B+A等长对齐，相遇为交点",
    "reverse-linked-list": "递归：head.next.next=head; head.next=null",
    "palindrome-linked-list": "递归后序+全局左指针，与右指针比较",
    "add-two-numbers-ii": "反转两链表后套用第2题做法",
    "middle-of-the-linked-list": "快指针到尾时，慢指针在中点",
    # Two Pointers
    "two-sum": "哈希表存补数下标",
    "container-with-most-water": "左右指针向中收缩，移动较短边",
    "3sum": "排序+去重，转化为双指针两数之和",
    "remove-duplicates-from-sorted-array": "快慢指针，慢指针仅在不重复时前进",
    "remove-element": "快慢指针原地覆盖目标值",
    "trapping-rain-water": "左右最大高度数组，水量=min(左最大,右最大)-高度",
    "sort-colors": "三路划分，追踪p0和p2指针",
    "remove-duplicates-from-sorted-array-ii": "快慢指针+计数，允许最多2个重复",
    "merge-sorted-array": "从末尾双指针逆向填充",
    "valid-palindrome": "去非字母数字字符，左右指针检验",
    "two-sum-ii-input-array-is-sorted": "左右指针，根据和与目标大小内移",
    "summary-ranges": "双指针(start,end)，连续则延伸，否则格式化区间",
    "move-zeroes": "快慢指针压缩非零元素，末尾补零",
    "reverse-string": "左右指针向中交换",
    "is-subsequence": "双指针遍历s和t，每次匹配推进t",
    "squares-of-a-sorted-array": "左右指针，较大的平方从末尾填入",
    "interval-list-intersections": "推进结束较早的区间指针，收集重叠",
    # Sliding Window
    "longest-substring-without-repeating-characters": "窗口字符计数，重复时左移",
    "substring-with-concatenation-of-all-words": "滑动窗口+词频Map，多起点偏移（0到词长）",
    "minimum-window-substring": "满足时收缩左边，记录最小窗口",
    "minimum-size-subarray-sum": "累积和>=目标时收缩左边，记最小长度",
    "contains-duplicate-ii": "集合维护窗口，超过k时移除左端",
    "contains-duplicate-iii": "TreeSet维护窗口，检查上下界是否在值域内",
    "longest-substring-with-at-least-k-repeating-characters": "枚举1-26种不同字符数，对每种找最长合法窗口",
    "longest-repeating-character-replacement": "记最高频字符，(窗口-最高频)>k时左移",
    "find-all-anagrams-in-a-string": "need/window双Map+valid计数，valid==need.size时记下标",
    "permutation-in-string": "同438，valid==need.size时返回true",
    "subarray-product-less-than-k": "合法窗口大小(right-left)即贡献的子数组数",
    "max-consecutive-ones-iii": "零的个数超k时左移，记最大窗口",
    "minimum-operations-to-reduce-x-to-zero": "转化为找最长子数组使其和=总和-x",
    # Binary Search
    "median-of-two-sorted-arrays": "二分较短数组，划分以找中位数",
    "find-first-and-last-position-of-element-in-sorted-array": "两次二分：左边界（收右）和右边界（收左）",
    "search-insert-position": "二分查找，未找到时返回left",
    "sqrtx": "在[1,x/2+1]二分，找最大mid使mid*mid<=x",
    "find-peak-element": "比较mid与邻居，确定有峰值的方向",
    "random-pick-with-weight": "前缀和数组，二分查找最右>=随机数[1,total]的下标",
    "binary-search": "标准闭区间二分",
    "koko-eating-bananas": "对吃香蕉速度二分，最小化耗时",
    "capacity-to-ship-packages-within-d-days": "对载重量二分，最小化天数函数",
    "maximum-profit-in-job-scheduling": "按开始时间排序，DP+二分找下一个可用任务",
    "kth-missing-positive-number": "线性扫描比较期望值与实际值，调整剩余k",
    "split-array-largest-sum": "对子数组最大和二分，最小化分割数",
    # Prefix Sum / Difference Array
    "range-sum-query-immutable": "预计算前缀和，查询用preSum[j+1]-preSum[i]",
    "range-sum-query-2d-immutable": "二维前缀和，容斥原理处理矩形查询",
    "car-pooling": "差分数组作用于站点，每处容量不超上限",
    "corporate-flight-bookings": "差分数组作用于航班，first到end-1区间加值",
    # Stack
    "valid-parentheses": "压入匹配的右括号，遇右括号弹出并验证",
    "simplify-path": "压入目录名，遇..弹出，忽略.，最后连接栈内容",
    "evaluate-reverse-polish-notation": "压数字，遇运算符弹两个计算后压回",
    "min-stack": "双栈，辅助栈记录每次push时的当前最小值",
    "implement-stack-using-queues": "记录栈顶，pop时将其余元素依次出队再入队",
    "implement-queue-using-stacks": "两个栈(top/bottom)，pop时将top倒入bottom",
    "longest-absolute-file-path": "用换行缩进深度管理栈，文件节点时计算完整路径长度",
    "maximum-frequency-stack": "freq到栈的映射+值到freq的映射，从最高频栈弹出",
    "number-of-recent-calls": "队列，移除3000ms窗口外的旧请求",
    "minimum-remove-to-make-valid-parentheses": "栈记录(的下标，不匹配的)加入删除列表，移除所有标记位置",
    # Monotonic Stack
    "remove-k-digits": "单调递增栈，从栈顶移除k个元素，处理前导零",
    "next-greater-element-i": "从nums2构建下一个更大元素Map，再查nums1",
    "next-greater-element-ii": "数组加倍模拟循环，构建下一个更大元素Map",
    "shortest-unsorted-continuous-subarray": "排序后找最左/最右位置原数组与排序数组不同处",
    "daily-temperatures": "单调栈存下标，遇到更高温度时弹出",
    "car-fleet": "按位置排序，计算到达时间，从后向前数递增序列",
    "online-stock-span": "栈存(值,跨度)，累计弹出元素的跨度",
    "next-greater-node-in-linked-list": "链表转数组，应用单调栈",
    "final-prices-with-a-special-discount-in-a-shop": "找下一个更小价格做差即折后价",
    "number-of-visible-people-in-a-queue": "统计从单调栈中弹出的元素数",
    # Binary Tree
    "validate-binary-search-tree": "向下传递min/max边界，节点违反则返回false",
    "binary-tree-level-order-traversal": "标准BFS逐层遍历",
    "binary-tree-zigzag-level-order-traversal": "BFS，按层奇偶交替addFirst/addLast",
    "maximum-depth-of-binary-tree": "深度=max(左,右)+1",
    "construct-binary-tree-from-preorder-and-inorder-traversal": "前序首元素为根，在中序中找根拆分左右",
    "construct-binary-tree-from-inorder-and-postorder-traversal": "后序末元素为根，在中序中找根拆分左右",
    "binary-tree-level-order-traversal-ii": "BFS用addFirst实现逆序输出",
    "flatten-binary-tree-to-linked-list": "展开左右子树，左子树尾接右子树，左置null",
    "populating-next-right-pointers-in-each-node": "遍历(node1,node2)对，覆盖三种兄弟关系",
    "populating-next-right-pointers-in-each-node-ii": "BFS逐层赋next指针",
    "sum-root-to-leaf-numbers": "DFS累积数值，叶子时累加",
    "binary-tree-preorder-traversal": "标准前序遍历",
    "binary-tree-right-side-view": "BFS记录每层最后元素；或前序DFS先走右子树",
    "count-complete-tree-nodes": "比较左右深度，相等时子树为满树(2^层-1)",
    "invert-binary-tree": "递归交换每个节点的左右子树",
    "lowest-common-ancestor-of-a-binary-tree": "节点等于p或q则返回，左右均非空则为LCA",
    "binary-tree-paths": "DFS带路径前缀，两子树均为null时记录",
    "serialize-and-deserialize-binary-tree": "前序加null节点序列化；或BFS层序",
    "verify-preorder-serialization-of-a-binary-tree": "非空节点入-1出+2，空节点入-1，初始边=1，为0时合法",
    "house-robber-iii": "树形DP，每节点返回(抢,跳)，抢=值+孙子之和",
    "find-largest-value-in-each-tree-row": "BFS记录每层最大值",
    "diameter-of-binary-tree": "当前节点直径=左深+右深，维护全局最大",
    "average-of-levels-in-binary-tree": "BFS对每层求平均",
    "find-duplicate-subtrees": "后序序列化每棵子树，频率Map检测重复",
    "maximum-binary-tree": "找最大值下标为根，递归构建左右子树",
    "maximum-width-of-binary-tree": "BFS带节点ID(左=2*id,右=2*id+1)，宽度=最后-最前+1",
    "construct-binary-tree-from-preorder-and-postorder-traversal": "前序首为根，在后序中找前序[start+1]确定左子树大小",
    "all-possible-full-binary-trees": "记忆化递归，n-1节点分为左(i)和右(n-1-i)",
    "check-completeness-of-a-binary-tree": "BFS，出现null后后续必须全为null",
    "smallest-string-starting-from-leaf": "DFS带字符串前缀，叶子处比较保留最小",
    "maximum-binary-tree-ii": "新值>根值时，新节点为根，旧根为其右子树；否则递归右边",
    "sum-of-root-to-leaf-binary-numbers": "DFS累积二进制值，叶子处累加",
    "delete-nodes-and-return-forest": "DFS追踪hasParent，被删节点的子节点成为新根",
    "maximum-level-sum-of-a-binary-tree": "BFS对每层求和，找最大",
    "deepest-leaves-sum": "BFS对最后一层求和",
    "pseudo-palindromic-paths-in-a-binary-tree": "DFS+大小10的计数数组，叶子处至多一个数字奇数次",
    "even-odd-tree": "BFS验证奇偶层约束",
    "lowest-common-ancestor-of-a-binary-tree-ii": "追踪p和q是否均找到，仅两者均确认时返回LCA",
    "lowest-common-ancestor-of-a-binary-tree-iii": "父指针构成链表，找两链表的交叉点",
    "lowest-common-ancestor-of-a-binary-tree-iv": "节点在目标集合中则返回，合并左右结果",
    # BST
    "unique-binary-search-trees-ii": "枚举根1到n，组合左右子树列表，记忆化",
    "unique-binary-search-trees": "卡特兰数DP：dp[n]=sum(dp[i-1]*dp[n-i])",
    "kth-smallest-element-in-a-bst": "中序遍历+全局计数器",
    "lowest-common-ancestor-of-a-binary-search-tree": "利用BST性质：节点值在val1和val2之间即为LCA",
    "delete-node-in-a-bst": "递归定位节点，双子树时用左子树最大值替换",
    "minimum-absolute-difference-in-bst": "中序遍历，追踪前驱节点，计算最小差值",
    "convert-bst-to-greater-tree": "反中序(右到根到左)，累计运行和",
    "search-in-a-binary-search-tree": "利用BST顺序递归查找",
    "insert-into-a-binary-search-tree": "递归左或右，到null时创建节点",
    "binary-search-tree-to-greater-sum-tree": "同第538题",
    # Graph
    "word-ladder": "BFS从beginWord出发，每步替换一个字符，过滤词典",
    "surrounded-regions": "将边缘O连接到哑节点，翻转所有未连接哑节点的O",
    "clone-graph": "BFS+旧到新节点Map，复制邻接表",
    "number-of-islands": "DFS洪泛，统计并展平每个岛屿",
    "course-schedule": "DFS+onPath数组检测环；或BFS Kahn入度算法",
    "course-schedule-ii": "BFS：按顺序追加入度0的节点；DFS：后序追加后反转",
    "minimum-height-trees": "迭代移除叶节点(度为1)，直到剩余<=2个",
    "longest-increasing-path-in-a-matrix": "DFS+记忆化，每格=1+合法邻居的最大值",
    "evaluate-division": "建带权图，BFS沿路径乘积边权",
    "number-of-provinces": "并查集，计算连通分量数",
    "redundant-connection": "并查集，两端点已连通则该边冗余",
    "number-of-distinct-islands": "DFS记录方向序列为字符串，集合统计不同形状",
    "max-area-of-island": "DFS洪泛，递归时追踪面积",
    "network-delay-time": "从源点Dijkstra，返回最大最短路径",
    "is-graph-bipartite": "BFS/DFS着色，相邻节点同色则返回false",
    "all-nodes-distance-k-in-binary-tree": "DFS建父指针Map，从目标BFS按深度追踪",
    "possible-bipartition": "同第785题",
    "minimize-malware-spread": "从每个初始节点BFS，候选=不含其他初始节点的最大分量",
    "most-stones-removed-with-same-row-or-column": "并查集合并共行或共列的石头，答案=石头数-分量数",
    "satisfiability-of-equality-equations": "合并相等变量，检查不等对是否在同一分量",
    "number-of-enclaves": "填充边缘连接的陆地，统计剩余1的个数",
    "number-of-closed-islands": "填充边缘连接的0-岛屿，统计剩余0-岛屿洪泛数",
    "validate-binary-tree-nodes": "入度0的节点为根，其余入度为1，从根遍历验证",
    "path-with-maximum-probability": "Dijkstra变体+最大堆，乘积路径概率",
    "min-cost-to-connect-all-points": "Kruskal算法，排序所有边后并查集",
    "path-with-minimum-effort": "Dijkstra变体，边权=最大绝对差",
    "count-sub-islands": "DFS：grid2岛屿中有grid1=0的格子则不是子岛，统计数量",
    "detonate-the-maximum-bombs": "按炸弹爆炸半径建有向图，BFS统计每个起点的可达数",
    # BFS
    "minimum-genetic-mutation": "BFS，每步单字符变换，返回步数",
    "01-matrix": "从所有0出发的多源BFS，向外传播距离",
    "open-the-lock": "BFS从0000出发，每步转动一格，过滤死锁和已访问",
    "sliding-puzzle": "BFS遍历状态字符串，生成所有下一状态",
    "keys-and-rooms": "从房间0 BFS收集钥匙，检查所有房间是否访问",
    "snakes-and-ladders": "以蛇形转换为1D索引的BFS，统计步数",
    "rotting-oranges": "从所有腐烂橙同时多源BFS，检查是否有新鲜橙剩余",
    "shortest-path-in-binary-matrix": "8方向BFS，统计到(n-1,n-1)的步数",
    "jump-game-iii": "BFS从下标跳+/-arr[index]，检查是否到达目标",
    "nearest-exit-from-entrance-in-maze": "从入口BFS，第一个非入口的空边界格为答案",
    # Backtracking
    "letter-combinations-of-a-phone-number": "回溯，遍历每个数字映射的所有字母",
    "sudoku-solver": "一维数组(i=index/9,j=index%9)，尝试数字，验证行/列/宫，递归",
    "combination-sum": "允许复用的回溯（用相同start递归）",
    "combination-sum-ii": "排序+跳过nums[i]==nums[i-1]，每元素仅用一次",
    "permutations": "回溯+used布尔数组",
    "permutations-ii": "排序+跳过nums[i]==nums[i-1]&&!used[i-1]",
    "n-queens": "追踪列、主对角线、反对角线集合，每行放一个皇后",
    "n-queens-ii": "同第51题，仅统计方案数",
    "combinations": "回溯+起始下标，避免重复",
    "subsets": "回溯+起始下标，记录所有前缀",
    "word-search": "网格回溯+visited追踪，检查边界",
    "gray-code": "从0回溯，每次变一位，检查是否已访问",
    "subsets-ii": "排序+同层跳过重复元素",
    "restore-ip-addresses": "选1-3个字符，验证后精确收集4段",
    "palindrome-partitioning": "尝试从start出发的所有子串，是回文则加入",
    "combination-sum-iii": "回溯+起始；恰好k个数字之和为n",
    "remove-invalid-parentheses": "尝试保留或删除每个括号，leftCount<0时剪枝",
    "matchsticks-to-square": "回溯分配到4个等和桶，超出最优或与前桶相同时剪枝",
    "non-decreasing-subsequences": "剪枝：值<上一个或本层已用则跳过",
    "beautiful-arrangement": "回溯1到n，检查start%i==0||i%start==0",
    "shopping-offers": "回溯遍历特惠组合，与不用特惠对比",
    "letter-case-permutation": "对每个字符分支大小写两种情况",
    "numbers-with-same-consecutive-differences": "逐位回溯，从末位+/-k分支",
    "unique-paths-iii": "DFS+used网格，统计访问所有非障碍格的路径数",
    "number-of-squareful-arrays": "排序+全排列回溯，相邻和非完全平方则剪枝",
    "letter-tile-possibilities": "排序拼字块，回溯+used，重复拼块时剪枝",
    "path-with-maximum-gold": "DFS+visited集合，尝试所有起点",
    "split-a-string-into-the-max-number-of-unique-substrings": "回溯，子串已出现则跳过，最大化唯一子串数",
    "find-minimum-time-to-finish-all-jobs": "回溯k个工人，超最优或工人负载与前相同时剪枝",
    "splitting-a-string-into-descending-consecutive-values": "回溯，不严格递减1时剪枝",
    "fair-distribution-of-cookies": "分配给k个小朋友，最小化最大值",
    "minimum-moves-to-spread-stones-over-grid": "从石头>1的格回溯到空格，追踪总步数",
    # Dynamic Programming
    "longest-palindromic-substring": "以每个中心向外扩展(i,j)，追踪最长",
    "jump-game-ii": "追踪当前和下一可达最远，到达边界时步数+1",
    "maximum-subarray": "dp[i]=max(dp[i-1]+nums[i],nums[i])，追踪全局最大",
    "jump-game": "追踪最大可达下标，确保i<=max",
    "unique-paths-ii": "dp[i][j]=dp[i-1][j]+dp[i][j-1]，障碍处置0",
    "minimum-path-sum": "dp[i][j]=min(dp[i-1][j],dp[i][j-1])+grid[i][j]",
    "edit-distance": "字符相等继承对角线，否则min(插入,删除,替换)+1",
    "interleaving-string": "dp[i][j]为true表示s1[0..i]和s2[0..j]可交错成s3[0..i+j]",
    "triangle": "dp[i][j]=min(dp[i-1][j-1],dp[i-1][j])+triangle[i][j]",
    "best-time-to-buy-and-sell-stock": "状态机DP含k次交易，追踪持有/未持有状态",
    "longest-consecutive-sequence": "排序或哈希集合，下一个数字存在则dp+1，否则重置为1",
    "integer-break": "dp[i]=max(j*max(dp[i-j],i-j))",
    "maximum-product-subarray": "同时追踪dpMax和dpMin，新极值取三者之最",
    "dungeon-game": "从右下角反向DP，dp[i][j]=max(1,min(下,右)-grid[i][j])",
    "house-robber": "dp[i]=max(dp[i-2]+nums[i],dp[i-1])",
    "house-robber-ii": "取rob(0..n-2)和rob(1..n-1)的最大值",
    "maximal-square": "cell为1时dp[i][j]=min(dp[i-1][j],dp[i-1][j-1],dp[i][j-1])+1",
    "longest-increasing-subsequence": "对每个i比较所有j<i且nums[j]<nums[i]，取最大长度",
    "coin-change": "dp[amount]=min(dp[amount-coin]+1)遍历所有硬币",
    "russian-doll-envelopes": "按宽度降序/高度升序排序，在高度上求LIS",
    "largest-divisible-subset": "排序，dp[i]=以nums[i]结尾且各元素整除后继的最大子集",
    "partition-equal-subset-sum": "0/1背包，目标=总和/2，布尔DP数组",
    "target-sum": "转化为子集和：目标=(target+sum)/2",
    "fibonacci-number": "从dp[0]=0,dp[1]=1迭代DP",
    "coin-change-ii": "无界背包，dp[j]+=dp[j-coin]",
    "delete-operation-for-two-strings": "len1+len2-2*LCS",
    "minimum-ascii-delete-sum-for-two-strings": "类编辑距离的2D DP，初始化为ASCII码之和",
    "maximum-length-of-repeated-subarray": "字符匹配时dp[i][j]=dp[i-1][j-1]+1，追踪最大",
    "delete-and-earn": "聚合同值的分数之和，然后做打家劫舍DP",
    "maximum-sum-circular-subarray": "max(Kadane结果，总和-最小子数组)",
    "minimum-falling-path-sum": "逐行DP，dp[i][j]=上方三个邻居之最小+grid值",
    "minimum-cost-for-tickets": "记忆化DFS，每个旅行日尝试1/7/30天票",
    "video-stitching": "按起点排序，贪心选择覆盖最远末点的片段",
    "last-stone-weight-ii": "找最接近sum/2的子集(0/1背包)，答案=总和-2*子集",
    "longest-common-subsequence": "字符相等则对角+1，否则取左/上最大",
    "greatest-sum-divisible-by-three": "追踪dp0/dp1/dp2，对每个数字更新",
    "solving-questions-with-brainpower": "反向DP：dp[i]=max(dp[i+难度+1]+分数, dp[i+1])",
    "count-ways-to-place-houses": "dp[i]=dp[i-1]+dp[i-2]，一侧结果的平方",
    # Greedy / Interval
    "gas-station": "前缀和，前缀和最小处+1为起点",
    "candy": "两遍贪心：左到右，再右到左，求和",
    "meeting-rooms-ii": "起止时间分别排序，双指针统计峰值并发数",
    "h-index": "降序排序，最大满足citations[i]>=论文数的i即为H指数",
    "non-overlapping-intervals": "按结束时间排序，贪心保留不重叠区间，统计移除数",
    "minimum-number-of-arrows-to-burst-balloons": "统计不重叠区域数，等端点也视为重叠",
    "ipo": "按资本排序，利润最大堆，贪心选最高可用利润",
    "insert-interval": "不重叠区间直接通过，重叠则合并新区间",
    "custom-sort-string": "统计字符，先按order顺序输出，再输出剩余",
    "mice-and-cheese": "按reward1-reward2降序排序，前k个给奶酪1",
    # Heap
    "ugly-number-ii": "追踪2,3,5的倍数索引，选最小下一丑数，推进索引",
    "find-median-from-data-stream": "最大堆(下半)+最小堆(上半)，保持大小平衡",
    "super-ugly-number": "PriorityQueue存(值,索引,质因子)元组，合并并去重",
    "find-k-pairs-with-smallest-sums": "PriorityQueue合并K个有序数组",
    "kth-smallest-element-in-a-sorted-matrix": "PriorityQueue合并有序行/对角线",
    "k-closest-points-to-origin": "按欧式距离平方排序，取前k个",
    # Design
    "lru-cache": "HashMap+双向链表，访问的条目移到头部",
    "insert-delete-getrandom-o1": "Map(值到下标)+列表，删除时与末尾元素交换",
    "complete-binary-tree-inserter": "BFS插入队列，维护有空子节点的节点",
    # Math / String
    "zigzag-conversion": "用方向标志分配字符到各行，在行0和numRows-1时反向",
    "palindrome-number": "转字符串，左右指针检验",
    "integer-to-roman": "将千/百/十/个位分别映射为罗马数字",
    "roman-to-integer": "从右到左遍历，当前<前一个则减，否则加",
    "longest-common-prefix": "按下标i逐字符比较所有字符串",
    "find-the-index-of-the-first-occurrence-in-a-string": "滑动遍历haystack，首字符匹配时比较子串",
    "powx-n": "快速幂：pow(x,n/2)的平方，处理负n和奇数n",
    "length-of-last-word": "去尾部空格，从末尾数到空格",
    "add-binary": "从右模拟二进制加法进位",
    "text-justification": "分组单词，分发空格（末行和单词行：左对齐）",
    "max-points-on-a-line": "对每个点i，将斜率(dx/gcd,dy/gcd)映射到计数",
    "reverse-words-in-a-string": "反转整个字符串，反转每个单词，去多余空格",
    "happy-number": "模拟各位平方和，用visited集合检测循环",
    "count-primes": "埃氏筛法，从i的平方开始标记倍数",
    "ugly-number": "反复除以2,3,5，结果为1则为丑数",
    "super-pow": "模1337的快速幂，递归计算",
    "ransom-note": "比较字符频率数组(大小26)",
    "stone-game": "先手必胜，先手总能选最优奇偶性",
    "ugly-number-iii": "对答案二分，用容斥原理和LCM统计倍数",
    # Bit Manipulation / Matrix / Randomized
    "rotate-image": "沿对角线转置，再逐行反转",
    "spiral-matrix": "维护左右上下边界，每遍后收缩",
    "spiral-matrix-ii": "同第54题，填充数值",
    "set-matrix-zeroes": "记录首行/列是否有零，用首行列作标记",
    "single-number-ii": "按value/10000索引的计数数组，过滤count为1的条目",
    "bitwise-and-of-numbers-range": "循环将right与right-1做AND，直到right<=left",
    "product-of-array-except-self": "左遍前缀积x右遍后缀积",
    "game-of-life": "三行滑动窗口追踪邻居数",
    "linked-list-random-node": "水库抽样：以1/index概率替换",
    "shuffle-an-array": "Fisher-Yates：位置i与随机>=i的位置交换",
    "random-pick-index": "水库抽样遍历所有匹配目标的下标",
    "construct-quad-tree": "递归拆成4个象限，子节点全同值时合并为叶子",
    "transpose-matrix": "新m*n数组，交换行列",
    "shift-2d-grid": "展平为1D，反转，再反转子段",
    "sort-the-matrix-diagonally": "用i-j作对角线键，排序并重建每条对角线",
    "time-needed-to-buy-tickets": "k之前的人买min(tickets,tickets[k])次，之后的买min(tickets,tickets[k]-1)次",
}

# Regex to match table rows with LeetCode links
row_pattern = re.compile(
    r'^(\| \[\d+\. [^\]]+\]\(https://leetcode\.com/problems/([^/]+)/\) \| )(.+?)( \|)\s*$'
)

with open(filepath, 'r', encoding='utf-8') as f:
    lines = f.readlines()

updated = 0
new_lines = []
for line in lines:
    m = row_pattern.match(line.rstrip('\n'))
    if m:
        prefix = m.group(1)
        slug = m.group(2)
        approach = m.group(3)
        suffix = m.group(4)
        if slug in translations and '（' not in approach:
            chinese = translations[slug]
            new_line = f"{prefix}{approach} （{chinese}）{suffix}\n"
            new_lines.append(new_line)
            updated += 1
        else:
            new_lines.append(line)
    else:
        new_lines.append(line)

with open(filepath, 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print(f"Done. Updated {updated} rows.")
